sadanandpai/resume-builder

src/App.tsx
src/components/core/settings-header/SettingsHeader.tsx
src/components/core/settings-header/TemplatesSettings.tsx
src/components/core/settings-header/ThemeSettings.tsx
src/components/pages/Resume.tsx
src/components/resume-templates/legacy-template/LegacyTemplate.tsx
src/components/resume-templates/legacy-template/core/RatingElement.tsx
src/components/resume-templates/legacy-template/core/SocialBar.tsx
src/components/resume-templates/professional-template/ProfessionalTemplate.tsx
src/components/resume-templates/professional-template/core/Section.tsx
src/components/resume-templates/professional-template/features/Exp.tsx
src/components/stores/settings.store.ts
src/components/stores/theme.store.ts

- Added templates into the header with selection functionality
- Added themes into the header with selection functionality
- Added keys in missing places for loops using the map
(UI is not developed. Dummy UI is used)

Templates and Themes core functionalities

---

src/components/core/settings-header/ItemSettings.tsx
src/components/core/settings-header/SettingsHeader.tsx
src/components/elements/PhotoElement.tsx
src/components/resume-templates/legacy-template/core/SectionHeader.tsx
src/components/resume-templates/legacy-template/core/SocialBar.tsx
src/components/resume-templates/professional-template/features/Description.tsx
src/components/stores/settings.store.ts

- Configurable photo element
- Minor color fixes to template

Configuration init

---

.eslintrc.json
.prettierrc
package.json

- Eslint and Prettier config added

🔨 Eslint and prettier config

---

src/core/components/editor/SkillsEdit.tsx
src/core/containers/LeftNav.tsx
src/core/containers/Sidebar.tsx
src/styles/icons.tsx

UI Fixes of icons and by default left and rightnav will be open

style: :lipstick: icon color change and draggable zindex

---

src/stores/data.store.ts

This updates the spelling of the word "Exposure"

Correct spelling for "Exposure"

---

src/__test__/index.test.tsx
src/modules/builder/nav-bar/NavBarLayout.tsx
src/pages/_app.tsx

fix: :lipstick: prepend test

---

src/helpers/constants/index.interface.ts
src/helpers/constants/index.ts
src/modules/builder/nav-bar/NavBarLayout.tsx
src/modules/builder/nav-bar/atoms/StyledButton.tsx
src/modules/builder/nav-bar/atoms/index.ts
src/modules/builder/nav-bar/components/MenuItem.interface.ts
src/modules/builder/nav-bar/components/MenuItem.tsx
src/modules/builder/nav-bar/components/NavMenuPopover.interface.ts
src/modules/builder/nav-bar/components/NavMenuPopover.tsx
src/modules/builder/nav-bar/components/ThemeSelect.tsx
src/styles/global.theme.ts

Adding support for custom colors as per the design, by overridding global MUI theme and navbar type interfaces moved to seperate files.

MUI global theme color overridden

---

package.json
src/helpers/constants/index.ts
src/modules/builder/nav-bar/NavBarLayout.tsx
src/modules/builder/nav-bar/components/TemplateSelect.tsx
src/modules/builder/nav-bar/components/TemplatesSlider.tsx
src/modules/builder/nav-bar/components/ThemeSelect.tsx

Template selection layout implementation.

Template selection layout

---

src/modules/builder/editor/modules/basic/BasicLayout.tsx

Basic Details layout with Contact and Links section
Adding Basic Details layout with Contact and Links section

Basic Details layout with Contact and Links section

---

src/modules/builder/editor/modules/skills/atoms/SkillPill.tsx

- Extend drag holder to full pill
- Center "delete" image inside the button
- Set "delete" image width and height to 16px

Extend drag to full pill, center delete image

---

src/modules/builder/editor/modules/education/EducationLayout.tsx
src/modules/builder/editor/modules/education/components/AddEducation.tsx
src/modules/builder/editor/modules/education/components/Education.tsx
src/modules/builder/editor/modules/experience/ExperienceLayout.tsx
src/stores/education.interface.ts
src/stores/education.ts
src/stores/experience.interface.ts

This PR includes the implementation of education layout

feat: ✨ education layout implementation

---

src/helpers/common/components/ErrorBoundary.tsx
src/helpers/constants/resume-data.json
src/modules/builder/editor/EditorLayout.tsx
src/modules/builder/editor/modules/education/components/Education.tsx
src/modules/builder/editor/modules/experience/components/Experience.tsx
src/stores/education.interface.ts
src/stores/experience.interface.ts
src/stores/index.interface.ts
src/stores/useResumeStore.tsx
src/templates/modern/components/Education.tsx
src/templates/modern/components/Work.tsx

- Education layout integration with template section
- Solved issues regarding date fields
- Added Errorboundary to side modal

Education layout integration with template section

---

src/helpers/constants/resume-data.json
src/modules/builder/editor/modules/basic/BasicLayout.tsx
src/modules/builder/editor/modules/basic/components/About.tsx
src/modules/builder/editor/modules/basic/components/BasicHeader.tsx
src/modules/builder/editor/modules/basic/components/BasicPanel.tsx
src/modules/builder/editor/modules/basic/components/Contacts.tsx
src/modules/builder/editor/modules/basic/components/Links.tsx
src/stores/basic.interface.ts
src/stores/basic.ts

The existing basic property is used from resume data json 

use the right properties from resume data json

---

src/helpers/constants/resume-data.json
src/modules/builder/editor/modules/awards/AwardsLayout.tsx
src/modules/builder/editor/modules/awards/components/AddAward.tsx
src/modules/builder/editor/modules/awards/components/Award.tsx
src/stores/awards.interface.ts
src/stores/awards.ts
src/stores/index.interface.ts
src/stores/useResumeStore.tsx
src/templates/modern/MordernTemplate.tsx
src/templates/modern/components/Awards.tsx
src/templates/professional/ProfessionalTemplate.tsx
src/templates/professional/components/Awards.tsx

Awards layout added templates and in side modal.

Side modal - Awards layout

---

src/modules/builder/editor/modules/awards/components/Award.tsx
src/templates/modern/components/Awards.tsx
src/templates/professional/components/Awards.tsx

Replacing text field in awards section with richtext editor

feat: ✨ richtext integration in awards section

---

src/helpers/common/components/richtext/index.tsx
src/modules/builder/editor/modules/experience/ExperienceLayout.tsx
src/modules/builder/editor/modules/experience/components/Experience.tsx
src/stores/experience.interface.ts
src/stores/experience.ts

fix: 🐛 richtext onchange maintains old state issue

---

src/modules/builder/editor/modules/awards/AwardsLayout.tsx
src/modules/builder/editor/modules/awards/components/Award.tsx
src/modules/builder/editor/modules/education/EducationLayout.tsx
src/modules/builder/editor/modules/education/components/Education.tsx
src/modules/builder/editor/modules/experience/components/Experience.tsx
src/stores/awards.interface.ts
src/stores/awards.ts
src/stores/education.interface.ts
src/stores/education.ts

feat: ✨ awards enhancement

---

src/helpers/constants/editor-data.ts
src/helpers/constants/resume-data.json
src/modules/builder/editor/modules/volunteering/Volunteering.tsx
src/modules/builder/editor/modules/volunteering/VolunteeringLayout.tsx
src/modules/builder/editor/modules/volunteering/components/AddVolunteering.tsx
src/modules/builder/editor/modules/volunteering/components/Volunteer.tsx
src/stores/volunteering.interface.ts
src/stores/volunteering.ts

feat: ✨ volunteering layout added

---

src/helpers/common/components/richtext/index.tsx
src/modules/builder/editor/modules/basic/BasicLayout.tsx
src/modules/builder/editor/modules/basic/components/About.tsx
src/stores/useResumeStore.tsx
src/templates/professional/components/AboutMe.tsx

Basic details rte changes made by sachin

Basic rte changes

---

package.json
src/helpers/common/atoms/Toast.tsx
src/helpers/constants/index.ts
src/modules/builder/editor/modules/awards/components/Award.tsx
src/modules/builder/editor/modules/basic/BasicLayout.tsx
src/modules/builder/editor/modules/education/components/Education.tsx
src/modules/builder/editor/modules/experience/components/Experience.tsx
src/modules/builder/editor/modules/skills/SkillsLayout.tsx
src/modules/builder/editor/modules/volunteering/components/Volunteer.tsx
src/modules/builder/nav-bar/NavBarLayout.tsx
src/stores/awards.interface.ts
src/stores/awards.ts
src/stores/basic.interface.ts
src/stores/basic.ts
src/stores/education.interface.ts
src/stores/education.ts
src/stores/experience.interface.ts
src/stores/experience.ts
src/stores/skill.interface.ts
src/stores/skills.ts
src/stores/volunteering.interface.ts
src/stores/volunteering.ts
src/templates/modern/components/Education.tsx
src/templates/professional/components/Education.tsx
src/templates/professional/components/Work.tsx

Import export

---

src/modules/builder/editor/modules/awards/AwardsLayout.tsx
src/modules/builder/editor/modules/basic/BasicLayout.tsx
src/modules/builder/editor/modules/basic/components/Contacts.tsx
src/modules/builder/editor/modules/basic/components/Links.tsx
src/modules/builder/editor/modules/education/EducationLayout.tsx
src/modules/builder/editor/modules/experience/ExperienceLayout.tsx
src/modules/builder/editor/modules/volunteering/VolunteeringLayout.tsx

Old data persist in right nav even after importing a new resume json issue fix

 basic section persist while importing new resume json issue

---

src/modules/builder/BuilderLayout.tsx
src/modules/builder/resume/ResumeLayout.tsx
src/modules/builder/resume/atoms/ResumeController.tsx
src/modules/builder/resume/components/ResumeHeader.tsx
src/stores/useZoom.tsx

- Reset zoom functionality added
- toggled the zoom-in and out icon for better UX
- while printing, reset the zoom position to 1
- fixed page cut while printing

fix: :bug: zoom and page cut fixed while printing

---

src/helpers/common/components/richtext/index.tsx
src/modules/builder/editor/modules/activities/ActivitiesLayout.tsx
src/modules/builder/editor/modules/activities/components/Achievements.tsx
src/modules/builder/editor/modules/activities/components/BasicHeader.tsx
src/modules/builder/editor/modules/activities/components/BasicPanel.tsx
src/modules/builder/editor/modules/activities/components/Involvements.tsx
src/modules/builder/nav-bar/NavBarLayout.tsx
src/stores/activity.interface.ts
src/stores/activity.ts

Activities

---

src/helpers/common/components/ValidSectionRenderer.tsx
src/templates/modern/MordernTemplate.tsx
src/templates/professional/ProfessionalTemplate.tsx

if content of a section is empty, removed the section from the layout.

Valid section renderer

---

src/modules/builder/nav-bar/components/TemplateSelect.tsx
src/modules/builder/nav-bar/components/TemplatesSlider.tsx

Tweak template selector layout
- slider arrow placement and list item layout
- selected tick placement
- selected template borders

Tweak layout of template selector

---

src/templates/professional/ProfessionalTemplate.tsx

- professional template font size changed to 12 px

style: :lipstick: professional template font size changed to 12 px

---

src/helpers/common/components/ProfileImage.tsx

-  Section validator for profile image

fix: :bug: Section validator for profile image

---

src/helpers/constants/resume-data.json
src/modules/builder/editor/modules/experience/components/AddExperience.tsx
src/modules/builder/editor/modules/experience/components/Experience.tsx
src/stores/experience.interface.ts
src/stores/experience.ts
src/stores/index.interface.ts
src/templates/professional/components/Work.tsx

Year of experience field added in experience.

feat: yoe field added in professional templates

---

src/modules/builder/BuilderLayout.tsx

- added a google feedback from in feedback button

fix: :memo: added a google feedback from in resume builder

---

src/helpers/constants/resume-data.json
src/modules/builder/resume/ResumeLayout.tsx
src/templates/modern/MordernTemplate.tsx
src/templates/modern/components/Awards.tsx
src/templates/modern/components/BasicIntro.tsx
src/templates/modern/components/Education.tsx
src/templates/modern/components/Volunteer.tsx
src/templates/modern/components/Work.tsx
src/templates/professional/ProfessionalTemplate.tsx
src/templates/professional/components/Objective.tsx

- modern resume style fix
- resume data modified

fix: :lipstick: Resume style fix and resume data added

---

.prettierrc
next-env.d.ts

-  added prettier and next env config files

chore: :wrench: added prettier and next env config files

---

src/modules/home/HomeLayout.tsx
src/modules/home/components/Person.tsx
src/pages/_app.tsx
src/templates/modern/atoms/ProfileContact.tsx
src/templates/modern/components/BasicIntro.tsx

refactor: :art: prettier and eslint fixes

---

README.md

resume builder readme updated
Readme udate

docs: :memo: resume builder readme updated

---

src/modules/home/HomeLayout.tsx
src/modules/home/components/Person.tsx
yarn.lock

- Add design story link
- Remove shadow around profile pictures

Tweak about us section 

---

README.md
next.config.js
src/modules/builder/nav-bar/NavBarLayout.tsx
src/modules/builder/nav-bar/components/TemplatesSlider.tsx

- Added redirect for v1 ```/editor``` route to ```/builder```
- Added disabled cursor for disabled template navigation arrows
- Added total templates count in top nav bar

Redirect support for old version routes 

---

package.json
src/pages/_app.tsx

Feat: Vercel analytics

---

src/modules/builder/nav-bar/atoms/NavBarActions.tsx
src/modules/home/HomeLayout.tsx
tailwind.config.js

- Added repo link in home page via github icon

feat: ✨ add github repo icon in home page

---

src/modules/home/HomeLayout.tsx
src/modules/home/components/Person.tsx

refactor: Persons section in home layout

---

.gitignore
.npmrc

Added since some storybook dependecies are not compatible with react v18

Added legacy peer deps as true due to issues while running npm install

---

src/helpers/common/atoms/Switch.tsx
src/helpers/icons/index.ts
src/modules/builder/editor/modules/basic/components/Links.tsx
src/templates/modern/MordernTemplate.tsx
src/templates/modern/atoms/SectionTitle.tsx
src/templates/modern/components/BasicIntro.tsx
src/templates/modern/components/Education.tsx
src/templates/modern/components/Skills.tsx
src/templates/professional/components/Education.tsx

Added icons will only show when profile image is empty

added libraries options in Skills Section  and links icons in only when Image is not Present modern template 

---

.github/workflows/ContinousIntegration.yaml
yarn.lock

Created ContinousIntegration.yaml Workflow to Automate Build & Test process for the Application

---

package-lock.json
package.json
src/stores/activity.ts
src/stores/awards.ts
src/stores/basic.ts
src/stores/education.ts
src/stores/experience.ts
src/stores/skills.ts
src/stores/store.interface.ts
src/stores/themes.ts
src/stores/useTemplate.ts
src/stores/useZoom.tsx
src/stores/volunteering.ts

Updated the store files to support latest version of Zustand along with immer

Zustand & immer migration

---

README.md
src/modules/home/components/Person.tsx

Update LinkedIn and GitHub links
